# Generated by Django 5.1.1 on 2024-09-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuxuryGlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('shade_name', models.CharField(max_length=100)),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
