# Generated by Django 5.1.1 on 2024-09-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_luxuryglow_skincaremakeupentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkincareMakeupEntry',
            new_name='Product',
        ),
    ]
